music = {
    # --- Global Hits ---
    "bad angel": "https://youtu.be/dKmPEhJ4wjY",
    "jump": "https://youtu.be/CgCVZdcKcqY",
    "apt": "https://youtu.be/ekr2nIex040",
    "waka waka": "https://youtu.be/pRpeEdMmmQ0",
    "despacito": "https://youtu.be/kJQP7kiw5Fk",
    "shape of you": "https://youtu.be/JGwWNGJdvx8",
    "blinding lights": "https://youtu.be/4NRXx6U8ABQ",
    "gangnam style": "https://youtu.be/9bZkp7q19f0",
    "uptown funk": "https://youtu.be/OPf0YbXqDM0",
    "see you again": "https://youtu.be/RgKAFK5djSk",
    "sugar": "https://youtu.be/09R8_2nJtjg",
    "sorry": "https://youtu.be/fRh_vgS2dFE",
    "counting stars": "https://youtu.be/hT_nvWreI6o",
    "roar": "https://youtu.be/CevxZvSJLk8",
    "thinking out loud": "https://youtu.be/lp-EO5I60KA",
    "dark horse": "https://youtu.be/0KSOMA3QBU0",
    "perfect": "https://youtu.be/2Vv-BfVoq4g",
    "faded": "https://youtu.be/60ItHLz5WEA",
    "let her go": "https://youtu.be/RBumgq5yVrA",
    "lean on": "https://youtu.be/YqeW9_5kURI",
    "danzakuduro": "https://youtu.be/7zp1TbLFPp8",
    "stay": "https://youtu.be/kTJczUociss",
    "levitating": "https://youtu.be/TUVcZfQe-Kw",
    "as it was": "https://youtu.be/H5v3kku4y6Q",
    "sunflower": "https://youtu.be/ApXoWvfEYVU",

    # --- Pakistani Hits (Coke Studio, Pop & Classics) ---
    "janaam fida haideri": "https://youtu.be/n8n_hkkhVCY",
    "pasoori": "https://youtu.be/5Eqb_-j3FDA",
    "tajdar e haram": "https://youtu.be/a18py61E8U4",
    "afreen afreen": "https://youtu.be/kw4tT7SCfiY",
    "kahani suno 2.0": "https://youtu.be/huX1o2n30v4",
    "tu jhoom": "https://youtu.be/7D4vNcK6D38",
    "zaroori tha": "https://youtu.be/6-n_szx2XRE",
    "kana yaari": "https://youtu.be/zQDAi8S_h8k",
    "blockbuster": "https://youtu.be/4eC9-7vUaJk",
    "sammi meri war": "https://youtu.be/2mDCVzrukLg",
    "baari": "https://youtu.be/h3_5O33Lzjs",
    "bol kaffara": "https://youtu.be/6S_H-iY_94c",
    "aaye kuch abr": "https://youtu.be/4tEw5I2M-r0",
    "bewafa": "https://youtu.be/8sL3677_xSo",
    "gal sun": "https://youtu.be/O3A1YmS1fmg",
    "woh lamhe": "https://youtu.be/sA36L9DOfdE",
    "aadat": "https://youtu.be/R93x3m49Qno",
    "teray liye": "https://youtu.be/S43dF5mY7yI",
    "bicho": "https://youtu.be/P_x4e0_9fR4",
    "ye jo halka halka suroor hai": "https://youtu.be/VJp5iW4N2W0",

    # --- Indian & Bollywood Hits ---
    "tum hi ho": "https://youtu.be/IJq0yyWug1k",
    "kesariya": "https://youtu.be/BddP6PYo2gs",
    "kal ho naa ho": "https://youtu.be/g0eO74UmREs",
    "chaiyya chaiyya": "https://youtu.be/PQmrm5s34GE",
    "raataan lambiyan": "https://youtu.be/gvyUuxdRdR4",
    "apna bana le": "https://youtu.be/ElZfdU54Cp8",
    "tere vaaste": "https://youtu.be/QcT81eMUpGk",
    "jai ho": "https://youtu.be/Yc5OyXmHD0w",
    "dil diyaan gallan": "https://youtu.be/SAcpESN_Fk4",
    "channa mereya": "https://youtu.be/284Ov7ysmfA",
    "ghungroo": "https://youtu.be/qFkNATtc3mc",
    "nashe si chhad gayi": "https://youtu.be/Wd2B8OAxyU8",
    "kaala chashma": "https://youtu.be/k4yXQkG2310",
    "galliyan": "https://youtu.be/1K2iN2U-XQ8",
    "pehli nazar mein": "https://youtu.be/Badge0J0yXk",
    "senorita": "https://youtu.be/9k_2E3mKk2I",
    "jeene laga hoon": "https://youtu.be/p8A-z_8-2tY",
    "tum se hi": "https://youtu.be/H2p9pT-l-S8",
    "agar tum saath ho": "https://youtu.be/sK7riqg254H",
    "kun faya kun": "https://youtu.be/T94PHkuydcw"
}