websites = {
    # --- Search Engines & AI ---
    "google": "https://google.com",
    "chatgpt": "https://chatgpt.com",
    "google gemini": "https://gemini.google.com/app",
    "bing": "https://bing.com",
    "duckduckgo": "https://duckduckgo.com",
    "claude": "https://claude.ai",
    "perplexity": "https://perplexity.ai",
    "yahoo": "https://yahoo.com",
    "baidu": "https://baidu.com",
    "yandex": "https://yandex.com",
    "ecosia": "https://ecosia.org",
    "qwant": "https://qwant.com",
    "startpage": "https://startpage.com",
    "open ai": "https://openai.com",
    "midjourney": "https://midjourney.com",
    "runway": "https://runwayml.com",
    "elevenlabs": "https://elevenlabs.io",
    "anthropic": "https://anthropic.com",
    "stability ai": "https://stability.ai",
    "poe": "https://poe.com",
    "character ai": "https://character.ai",

    # --- Social Media & Networking ---
    "facebook": "https://facebook.com",
    "instagram": "https://instagram.com",
    "x": "https://x.com",
    "twitter": "https://twitter.com",
    "linkedin": "https://linkedin.com",
    "reddit": "https://reddit.com",
    "pinterest": "https://pinterest.com",
    "tiktok": "https://tiktok.com",
    "snapchat": "https://snapchat.com",
    "discord": "https://discord.com",
    "whatsapp": "https://whatsapp.com",
    "telegram": "https://telegram.org",
    "threads": "https://threads.net",
    "tumblr": "https://tumblr.com",
    "quora": "https://quora.com",
    "wechat": "https://wechat.com",
    "weibo": "https://weibo.com",
    "mastodon": "https://mastodon.social",
    "bluesky": "https://bsky.app",
    "vk": "https://vk.com",
    "line": "https://line.me",
    "viber": "https://viber.com",
    "signal": "https://signal.org",
    "nextdoor": "https://nextdoor.com",
    "meetup": "https://meetup.com",
    "untappd": "https://untappd.com",
    "foursquare": "https://foursquare.com",

    # --- Video Streaming & Audio ---
    "youtube": "https://youtube.com",
    "netflix": "https://netflix.com",
    "twitch": "https://twitch.tv",
    "vimeo": "https://vimeo.com",
    "hulu": "https://hulu.com",
    "disney plus": "https://disneyplus.com",
    "amazon prime video": "https://primevideo.com",
    "max": "https://max.com",
    "spotify": "https://spotify.com",
    "apple music": "https://music.apple.com",
    "soundcloud": "https://soundcloud.com",
    "dailymotion": "https://dailymotion.com",
    "deezer": "https://deezer.com",
    "tidal": "https://tidal.com",
    "pandora": "https://pandora.com",
    "bandcamp": "https://bandcamp.com",
    "audible": "https://audible.com",
    "crunchyroll": "https://crunchyroll.com",
    "paramount plus": "https://paramountplus.com",
    "peacock": "https://peacocktv.com",
    "rumble": "https://rumble.com",
    "mixcloud": "https://mixcloud.com",
    "shazam": "https://shazam.com",

    # --- Developer, Tech & Cloud ---
    "github": "https://github.com",
    "gitlab": "https://gitlab.com",
    "stack overflow": "https://stackoverflow.com",
    "bitbucket": "https://bitbucket.org",
    "npm": "https://npmjs.com",
    "pypi": "https://pypi.org",
    "docker": "https://docker.com",
    "hugging face": "https://huggingface.co",
    "codepen": "https://codepen.io",
    "replit": "https://replit.com",
    "w3schools": "https://w3schools.com",
    "developer mozilla": "https://developer.mozilla.org",
    "leetcode": "https://leetcode.com",
    "kaggle": "https://kaggle.com",
    "vercel": "https://vercel.com",
    "netlify": "https://netlify.com",
    "aws": "https://aws.amazon.com",
    "google cloud": "https://cloud.google.com",
    "azure": "https://azure.microsoft.com",
    "digitalocean": "https://digitalocean.com",
    "cloudflare": "https://cloudflare.com",
    "supabase": "https://supabase.com",
    "firebase": "https://firebase.google.com",
    "postman": "https://postman.com",
    "hackerrank": "https://hackerrank.com",
    "codecademy": "https://codecademy.com",
    "freecodecamp": "https://freecodecamp.org",
    "geeksforgeeks": "https://geeksforgeeks.org",
    "jsfiddle": "https://jsfiddle.net",
    "codesandbox": "https://codesandbox.io",
    "dev.to": "https://dev.to",
    "hashnode": "https://hashnode.com",
    "linode": "https://linode.com",

    # --- E-Commerce & Retail ---
    "amazon": "https://amazon.com",
    "ebay": "https://ebay.com",
    "aliexpress": "https://aliexpress.com",
    "walmart": "https://walmart.com",
    "target": "https://target.com",
    "etsy": "https://etsy.com",
    "shopify": "https://shopify.com",
    "alibaba": "https://alibaba.com",
    "rakuten": "https://rakuten.com",
    "best buy": "https://bestbuy.com",
    "craigslist": "https://craigslist.org",
    "temu": "https://temu.com",
    "shein": "https://shein.com",
    "home depot": "https://homedepot.com",
    "ikea": "https://ikea.com",
    "wayfair": "https://wayfair.com",
    "costco": "https://costco.com",
    "flipkart": "https://flipkart.com",
    "poshmark": "https://poshmark.com",
    "mercari": "https://mercari.com",
    "newegg": "https://newegg.com",
    "overstock": "https://overstock.com",
    "zappos": "https://zappos.com",
    "asos": "https://asos.com",

    # --- Productivity, Design & Collaboration ---
    "notion": "https://notion.so",
    "trello": "https://trello.com",
    "slack": "https://slack.com",
    "zoom": "https://zoom.us",
    "google drive": "https://drive.google.com",
    "dropbox": "https://dropbox.com",
    "canva": "https://canva.com",
    "figma": "https://figma.com",
    "jira": "https://atlassian.com/software/jira",
    "asana": "https://asana.com",
    "airtable": "https://airtable.com",
    "google docs": "https://docs.google.com",
    "microsoft office": "https://office.com",
    "miro": "https://miro.com",
    "basecamp": "https://basecamp.com",
    "clickup": "https://clickup.com",
    "monday": "https://monday.com",
    "evernote": "https://evernote.com",
    "todoist": "https://todoist.com",
    "loom": "https://loom.com",
    "adobe": "https://adobe.com",
    "behance": "https://behance.net",
    "dribbble": "https://dribbble.com",
    "fiverr": "https://fiverr.com",
    "upwork": "https://upwork.com",
    "freelancer": "https://freelancer.com",
    "grammarly": "https://grammarly.com",
    "wetransfer": "https://wetransfer.com",
    "surveymonkey": "https://surveymonkey.com",
    "typeform": "https://typeform.com",

    # --- News, Media & Publishing ---
    "wikipedia": "https://wikipedia.org",
    "the new york times": "https://nytimes.com",
    "bbc": "https://bbc.com",
    "cnn": "https://cnn.com",
    "the guardian": "https://theguardian.com",
    "forbes": "https://forbes.com",
    "bloomberg": "https://bloomberg.com",
    "reuters": "https://reuters.com",
    "medium": "https://medium.com",
    "substack": "https://substack.com",
    "wikihow": "https://wikihow.com",
    "imdb": "https://imdb.com",
    "the washington post": "https://washingtonpost.com",
    "wall street journal": "https://wsj.com",
    "huffpost": "https://huffpost.com",
    "buzzfeed": "https://buzzfeed.com",
    "techcrunch": "https://techcrunch.com",
    "the verge": "https://theverge.com",
    "wired": "https://wired.com",
    "arstechnica": "https://arstechnica.com",
    "engadget": "https://engadget.com",
    "ign": "https://ign.com",
    "national geographic": "https://nationalgeographic.com",
    "time": "https://time.com",
    "business insider": "https://businessinsider.com",

    # --- Travel, Food & Maps ---
    "booking": "https://booking.com",
    "airbnb": "https://airbnb.com",
    "tripadvisor": "https://tripadvisor.com",
    "expedia": "https://expedia.com",
    "google maps": "https://maps.google.com",
    "uber": "https://uber.com",
    "lyft": "https://lyft.com",
    "doordash": "https://doordash.com",
    "ubereats": "https://ubereats.com",
    "grubhub": "https://grubhub.com",
    "kayak": "https://kayak.com",
    "skyscanner": "https://skyscanner.com",
    "yelp": "https://yelp.com",
    "opentable": "https://opentable.com",
    "zillow": "https://zillow.com",
    "redfin": "https://redfin.com",
    "realtor": "https://realtor.com",
    "vrbo": "https://vrbo.com",
    "instacart": "https://instacart.com",

    # --- Finance, Banking & Crypto ---
    "paypal": "https://paypal.com",
    "stripe": "https://stripe.com",
    "wise": "https://wise.com",
    "coinbase": "https://coinbase.com",
    "robinhood": "https://robinhood.com",
    "yahoo finance": "https://finance.yahoo.com",
    "tradingview": "https://tradingview.com",
    "binance": "https://binance.com",
    "revolut": "https://revolut.com",
    "venmo": "https://venmo.com",
    "mint": "https://mint.intuit.com",
    "marketwatch": "https://marketwatch.com",
    "investopedia": "https://investopedia.com",
    "coingecko": "https://coingecko.com",
    "coinmarketcap": "https://coinmarketcap.com",
    "chase": "https://chase.com",
    "bank of america": "https://bankofamerica.com",
    "wells fargo": "https://wellsfargo.com",

    # --- Education & Learning ---
    "coursera": "https://coursera.org",
    "udemy": "https://udemy.com",
    "edx": "https://edx.org",
    "khan academy": "https://khanacademy.org",
    "duolingo": "https://duolingo.com",
    "quizlet": "https://quizlet.com",
    "skillshare": "https://skillshare.com",
    "scribd": "https://scribd.com",
    "masterclass": "https://masterclass.com",
    "babbel": "https://babbel.com",
    "memrise": "https://memrise.com",
    "researchgate": "https://researchgate.net",
    "academia": "https://academia.edu",
    "jstor": "https://jstor.org",
    "wolfram alpha": "https://wolframalpha.com",
    "pluralsight": "https://pluralsight.com",

    # --- Gaming ---
    "steam": "https://store.steampowered.com",
    "epic games": "https://epicgames.com",
    "roblox": "https://roblox.com",
    "playstation": "https://playstation.com",
    "xbox": "https://xbox.com",
    "nintendo": "https://nintendo.com",
    "gog": "https://gog.com",
    "itch.io": "https://itch.io",
    "nexus mods": "https://nexusmods.com",
    "chess": "https://chess.com",
    "lichess": "https://lichess.org",
    "ign": "https://ign.com",
    "gamespot": "https://gamespot.com",

    # --- Utilities, Health & Miscellaneous ---
    "weather": "https://weather.com",
    "accuweather": "https://accuweather.com",
    "speedtest": "https://speedtest.net",
    "archive.org": "https://archive.org",
    "patreon": "https://patreon.com",
    "kickstarter": "https://kickstarter.com",
    "indiegogo": "https://indiegogo.com",
    "change.org": "https://change.org",
    "gofundme": "https://gofundme.com",
    "webmd": "https://webmd.com",
    "healthline": "https://healthline.com",
    "mayoclinic": "https://mayoclinic.org",
    "giphy": "https://giphy.com",
    "tenor": "https://tenor.com",
    "unsplash": "https://unsplash.com",
    "pexels": "https://pexels.com",
    "pixabay": "https://pixabay.com",
    "imgur": "https://imgur.com",
    "tinyurl": "https://tinyurl.com",
    "bitly": "https://bitly.com"
}